# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
